@startuml

!define object << (O,LightSeaGreen) >>
!define model << (M,LightSalmon) >>

title Data Models


class User model {
  +username: String
  +firstname: String
  +lastname: String
  +email: String
  +roles: [String]
  == Virtual ==
  +fullName: String
  +url: String
}

class Blog model {
  +category: String
  == Virtual ==
  +url: String
}

class Comment model {
  +post: ObjectId
  +body: String
  +author: ObjectId
}

class Reaction model {
  +targetId: ObjectId
  +reactionType: String
  +reactingUserId: ObjectId
}

class Post model {
  +title: String
  +body: String
  == Virtual ==
  +url: String
}

' A Comment has 1 User (creator) 
' A User has 0 or more comments
User "1" -- "0.." Comment : creates

' A user has 0 or more Posts
' A Post has 1 or more Users (creators)
User "1.." -- "0.." Post : creates

' A Blog has 0 or more Posts 
' A Post has 1 Blog
Blog "1" -- "0.." Post : contains

' A Reaction has 0 or more Posts 
' A Post has 0 or more Reactions
Post "0.." -- "0.." Reaction : contains

' A Comment has 0 or more Reactions
' A Reaction has 0 or more Comments 
Comment "0.." -- "0.." Reaction : contains 

' A Post has 0 or more Comments
' A Comment has 1 Post
Post "1" -- "0.." Comment  : contains

@enduml