@startuml 0_initial-request.puml

!include utils.puml

group ===Initial Request {
  start
  $neutral_action("Client Request Recieved")
  $if_then_success("valid endpoint?","Forward Request to Controller")
  $else_error("404")
  endif
}

#Orchid:(0)

@enduml