@startuml 1_process-request.puml

!include utils.puml
!include 0-initial-request.puml


group ===Process Request {
  :Controller Recieves Request;
  if(route protected?) then (true)
  :Authenticate;
  else(false)
  :next;
  endif
  $success_with_error("Client Request Recieved","valid endpoint?","Send the Request to Controller","404")
}

@enduml