@startuml 1_process-request.puml

!include utils.puml

group ===Registration Request POST {
  $input_received("Registration Data")
  :Sanitize;
  $if_then_success("validation successful?","Create User")
  endif
  ' $next_with_error("Validate","validation successful?","Create User")
}

@enduml