@startuml

!include definitions.puml

!function $purple_label($text) !return "#text:Purple : "+$text
!$association_line="-[#MidnightBlue]-"

title Model Associations

' Relationships
' A Comment references 1 User (creator) 
' A User references 0 or more comments
User "1" $association_line "*" Comment $purple_label(creates)

' A User references 0 or more Posts
' A Post references 1 or more Users (creators)
User "1..*" $association_line "*" Post $purple_label(creates)

' A Blog references 0 or more Posts 
' A Post references 1 Blog
Blog "1" $association_line "*" Post $purple_label(references)

' A Reaction references 0 or more Posts 
' A Post references 0 or more Reactions
Post "*" $association_line "*" Reaction $purple_label(references)

' A Comment references 0 or more Reactions
' A Reaction references 0 or more Comments 
Comment "*" $association_line "*" Reaction $purple_label(references) 

' A Comment references 0 or 1 Comment (parent/reply)
Comment $association_line "0..1" Comment $purple_label(references)

' A Post references 0 or more Comments
' A Comment references 1 Post
Post "1" $association_line "*" Comment $purple_label(references)

'An APIKey references 1 User
'A User references 0 APIKeys
APIKey "0" $association_line "1" User $purple_label(references)

' A Profile references 1 User
' A User references 0 Profiles
Profile "0" $association_line "1" User $purple_label(references)

@enduml