@startuml

!include definitions.puml

!function $association_line() !return "-[#MidnightBlue]-"

title Model Associations

' Relationships
' A Comment references 1 User (creator) 
' A User references 0 or more comments
User "1" $association_line() "0.." Comment #text:Purple : creates

' A user references 0 or more Posts
' A Post references 1 or more Users (creators)
User "1.." $association_line() "0.." Post #text:Purple : creates

' A Blog references 0 or more Posts 
' A Post references 1 Blog
Blog "1" $association_line() "0.." Post #text:Purple : references

' A Reaction references 0 or more Posts 
' A Post references 0 or more Reactions
Post "0.." $association_line() "0.." Reaction #text:Purple : references

' A Comment references 0 or more Reactions
' A Reaction references 0 or more Comments 
Comment "0.." $association_line() "0.." Reaction #text:Purple : references 

' A Comment can reference 1 other Comment (parent/reply)
Comment $association_line() "0..1" Comment #text:Purple : references

' A Post references 0 or more Comments
' A Comment references 1 Post
Post "1" $association_line() "0.." Comment #text:Purple : references

@enduml