@startuml

!function $document_model($alias) !return "class " + $alias + "<< (M,SkyBlue) >> #LightSteelBlue"

!procedure $id() 
_id: ObjectId
--
!endprocedure

!procedure $timestamp()
+createdAt: Date
+updatedAt: Date
!endprocedure

title Model Definitions

$document_model(User) {
  $id()
  +username: String
  +firstname: String
  +lastname: String
  +email: String
  +roles: [String]
  $timestamp()
  == Virtual ==
  +fullName: String
  +url: String
} 

$document_model(Blog) {
  $id()
  +category: String
  +tags: [String]
  $timestamp()
  == Virtual ==
  +url: String
}

$document_model(Comment) {
  $id()
  +postId: ObjectId
  +parentCommentId: ObjectId
  +body: String
  +authorId: ObjectId
  $timestamp()
  == Virtual ==
  +url: String
}

$document_model(Reaction) {
  $id()
  +targetId: ObjectId
  +reactionType: String
  +reactingUserId: ObjectId
  $timestamp()
  == Virtual ==
  +url: String
}

$document_model(Post) {
  $id()
  +authorId: [ObjectId]
  +blogId: ObjectId
  +title: String
  +body: String
  +views: Number
  +status: String
  $timestamp()
  == Virtual ==
  +url: String
}

@enduml