@startuml

!include definitions.puml

!function $reaction_reference() !return "-[#DarkOliveGreen]-->"
!function $comment_reference() !return "-[#MidnightBlue]-->"
!function $post_reference() !return "-[#Purple]-->"

skinparam group 2

title Model References

together {
  ' Reaction references ONE Post OR Comment
  Reaction::targetId $reaction_reference() Post::_id #text:DarkGreen : Post._id
  Reaction::targetId $reaction_reference() Comment::_id #text:DarkGreen : Comment._id
  ' Reaction references ONE User (author)
  Reaction::reactingUserId $reaction_reference() User::_id #text:DarkGreen : User._id
}
together {
  ' Comment references ONE Post
  Comment::postId $comment_reference() Post::_id #text:DarkBlue : Post._id
  ' Comment references ONE Comment (parent/reply)
  Comment::parentCommentId $comment_reference() Comment::_id #text:DarkBlue : Comment::_id 
  ' Comment references ONE User (author) 
  Comment::authorId $comment_reference() User::_id #text:DarkBlue : User._id
}
together {
  ' Post references ONE Blog
  Post::blogId $post_reference() Blog::_id #text:DarkOrchid : Blog._id
  ' Post references ONE or MORE(few) User(s) (authors)
  Post::authorId $post_reference() User::_id #text:DarkOrchid : User._id
}
@enduml